### Login sebagai pengguna dan dapatkan token
POST http://localhost/api/login
Content-Type: application/json

{
  "email": "beta@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Kirim donasi sebagai pengguna yang sudah login
POST http://localhost/api/donations
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "campaign_id": 1,
  "amount": 100000
}
